# Generated by Django 4.0.6 on 2022-08-02 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_remove_following_following_following_followings_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
